version: '3.8'

services:
    db:
        image: mysql:8
        container_name: evaluation_tool_db
        restart: unless-stopped
        ports:
            - ${SQL_LOCAL_PORT}:${SQL_DOCKER_PORT}
        environment:
            - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${SQL_DATABASE}

    backend:
        image: eval_tool_backend
        build: .
        container_name: evaluation_tool_backend
        environment:
            - SQL_HOST=db
            - SQL_NAME=${SQL_DATABASE}
            - SQL_USER=${SQL_USER}
            - SQL_PASSWORD=${SQL_ROOT_PASSWORD}
            - SQL_PORT=${SQL_DOCKER_PORT}
        # Let it sleep, we will set it inside docker container
        command: sleep infinity
        volumes:
            - ./project:/project/
        ports:
            - ${BACKEND_LOCAL_PORT}:${BACKEND_DOCKER_PORT}
        depends_on:
            - db