version: '3.8'

services:
    redis:
        image: redis:8.2.3-alpine
        ports:
            - 6380:${REDIS_PORT}
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

    db:
        image: postgres:18.1-alpine
        container_name: user_management_db
        restart: unless-stopped
        ports:
            - 5433:${POSTGRES_PORT}
        env_file:
            - .env

    backend:
        image: user_management_service
        build: .
        container_name: user_management_service
        env_file:
            - .env 
        # Let it sleep, we will set it inside docker container
        command: sleep infinity
        volumes:
            - ./project:/project/
        ports:
            - 8001:8000
        depends_on:
            - db
            - redis