name: "sonar_scan"
on:
  pull_request:
    branches:
      - main

jobs:
  sonar_scan:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tox
      run: tox -e py
    - name: Run SonarCloud Scanner
      uses: SonarSource/sonarqube-scan-action@v4.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=fevaltool
          -Dsonar.projectKey=FEvalTool_Evaluation-Tool-Backend